import Head from "next/head";
import About from "./about";
import Education from "./education";
import Services from "./services";
import Projects from "./projects";
import TechStack from "./techstack";
import ContactMe from "./contact";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Kshitij&apos;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center px-10 md:px-20 lg:px-40 pt-20" style={{ backgroundColor: '#FF6500' }}>
        <nav className="fixed top-0 left-0 w-full py-5 bg-black z-50 flex justify-between px-10 md:px-20 lg:px-40">
          <h1 className="font-burtons text-xl text-white">kshitij gurbuxani</h1>
          <ul className="flex items-center space-x-6">
            <li>
              <a className="text-white px-4 py-2 border-none rounded-md transition duration-300 hover:scale-105 hover:text-[#FF6500]" href="#about">About</a>
            </li>
            <li>
              <a className="text-white px-4 py-2 border-none rounded-md transition duration-300 hover:scale-105 hover:text-[#FF6500]" href="#education">Education</a>
            </li>
            <li>
              <a className="text-white px-4 py-2 border-none rounded-md transition duration-300 hover:scale-105 hover:text-[#FF6500]" href="#techstack">Tech Stack</a>
            </li>
            <li>
              <a className="text-white px-4 py-2 border-none rounded-md transition duration-300 hover:scale-105 hover:text-[#FF6500]" href="#services">Services</a>
            </li>
            <li>
              <a className="text-white px-4 py-2 border-none rounded-md transition duration-300 hover:scale-105 hover:text-[#FF6500]" href="#projects">Projects</a>
            </li>
            <li>
              <a className="text-white px-4 py-2 border-none rounded-md transition duration-300 hover:scale-105 hover:text-[#FF6500]" href="#contact">Contact Me</a>
            </li>
            <li>
              <a className="text-white px-4 py-2 border-none rounded-md transition duration-300 hover:scale-105 hover:text-[#FF6500]" href="https://drive.google.com/file/d/1yG_tcfhRys2zHw7uDh84KvcmbuRua7XC/view?usp=sharing">Resume</a>
            </li>
          </ul>
        </nav>
        <section className="min-h-screen flex flex-col items-center" style={{ backgroundColor: '#FF6500' }}>
          <section id="about" className="mb-4 w-full flex justify-center">
            <About />
          </section>
          <section id="education" className="mb-4 w-full flex justify-center">
            <Education />
          </section>
          <section id="techstack" className="mb-4 w-full flex justify-center">
            <TechStack />
          </section>
          <section id="services" className="mb-4 w-full flex justify-center">
            <Services />
          </section>
          <section id="projects" className="mb-0 w-full flex justify-center">
            <Projects />
          </section>
          <section id="contact" className="mb-4 w-full flex justify-center">
            <ContactMe />
          </section>
        </section>
      </main>
      <footer className="w-full py-4 bg-black text-white text-center">
        © 2024 Kshitij Gurbuxani. All rights reserved.
      </footer>
    </div>
  );
}
